#!/usr/bin/env python3
"""Regenerate the Q14 registry entry from the effective cohort.

    python cohorts/build_registry.py

Run it after every `select.py`, read the diff, commit it. The output file is
GENERATED — edit this script or the cohort, never the YAML.

One source, one endpoint per cohort member. Not one source per molecule: they
share a schema, a cadence and a host, and 275 near-identical registry files
would be noise rather than reviewable additions. Sharding parallelises across
sources, so keeping them in one source is also what keeps 275 requests off
openFDA in parallel.
"""
from __future__ import annotations

import sys
from pathlib import Path
from urllib.parse import quote

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from wss.cohort import effective_members  # noqa: E402

REPO = Path(__file__).resolve().parents[1]
COHORT = REPO / "cohorts" / "injectable-generics"
OUT = REPO / "registry" / "fda.drugsfda.cohort-status.yml"

HEADER = '''# GENERATED by cohorts/build_registry.py — do not edit by hand.
# Regenerate after each cohort selection; edit the script or the cohort.
#
# Q14: do suppliers leave BEFORE a shortage or after it? Drugs@FDA gives each
# product's CURRENT marketing_status and NO discontinuation date — not in the
# API, and not in FDA's own bulk MarketingStatus.txt, which is
# `MarketingStatusID | ApplNo | ProductNo` and nothing else. Watching the count
# per molecule is what turns an exit into a dated event.
#
# One `count=products.marketing_status` query per molecule returns exactly the
# numbers the question needs — {{"Discontinued": 33, "Prescription": 4}} — in
# about 400 bytes. {members} molecules is ~{kb:.0f} KB per capture, ~{mb:.1f} MB/yr
# monthly. Capturing all 29,298 applications instead would cost ~114 MB/yr for
# strictly less signal per byte.
#
# Membership is the frozen `injectable-generics` cohort: injectable generics
# whether or not they are short, so that an exit preceding a shortage can
# actually be observed, and once in never out so the dead stay visible.
# See cohorts/select.py.
source_id: fda.drugsfda.cohort-status
status: paused  # flip to active when you want Q14 running
cadence: monthly
schema_id: fda-drugsfda-count.v1

publisher: US Food and Drug Administration
publisher_tier: first_party
destroys_own_history: true
licence: "US federal work, no copyright in the US; https://open.fda.gov/terms/"
personal_data: none
storage: git

notes: >-
  Every ingredient string here was verified to resolve in Drugs@FDA at
  selection time; unresolvable names (mostly multi-ingredient combinations,
  which have no single active_ingredients.name) are excluded by select.py
  rather than left as permanently failing endpoints. The parser reads the
  ingredient back out of the URL, so entity ids stay stable across vintages.

gates:
  expect_status: 200
  min_bytes: 150
  content_type_any: [json]
  must_contain: ["results", "term"]
  must_not_contain: ["NOT_FOUND"]

endpoints:
'''


def main() -> None:
    # effective_members returns {entity_id: {...}} — the union across every
    # vintage, so a molecule that dies keeps its endpoint forever.
    names = sorted(effective_members(COHORT))
    kb = len(names) * 0.4
    body = HEADER.format(members=len(names), kb=kb, mb=kb * 12 / 1024)
    lines = [body]
    for name in names:
        search = quote(f'products.active_ingredients.name:"{name}"', safe="")
        lines.append(
            f'  - url: "https://api.fda.gov/drug/drugsfda.json'
            f'?search={search}&count=products.marketing_status"\n'
            f"    delay_seconds: 3\n")
    OUT.write_text("".join(lines), encoding="utf-8")
    print(f"wrote {OUT.relative_to(REPO)} — {len(names)} endpoints, "
          f"~{kb:.0f} KB/capture, ~{kb * 12 / 1024:.1f} MB/yr")


if __name__ == "__main__":
    main()
